# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sweepergui(object):
    def setupUi(self, sweepergui):
        sweepergui.setObjectName("sweepergui")
        sweepergui.resize(900, 511)
        sweepergui.setMinimumSize(QtCore.QSize(900, 0))
        self.gridLayout = QtWidgets.QGridLayout(sweepergui)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(sweepergui)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(sweepergui)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 2, 1, 1)
        self.mplwindow = QtWidgets.QWidget(sweepergui)
        self.mplwindow.setMinimumSize(QtCore.QSize(0, 0))
        self.mplwindow.setBaseSize(QtCore.QSize(0, 0))
        self.mplwindow.setObjectName("mplwindow")
        self.mplvl = QtWidgets.QVBoxLayout(self.mplwindow)
        self.mplvl.setContentsMargins(0, 0, 0, 0)
        self.mplvl.setObjectName("mplvl")
        self.gridLayout.addWidget(self.mplwindow, 0, 0, 7, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(sweepergui)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setMaximum(65000)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setEnabled(False)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.groupBox_4)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(sweepergui)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pocetMereniBox = QtWidgets.QSpinBox(self.groupBox)
        self.pocetMereniBox.setMinimum(1)
        self.pocetMereniBox.setMaximum(20)
        self.pocetMereniBox.setObjectName("pocetMereniBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pocetMereniBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.groupBox_3)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setMaximum(30)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 2)
        self.startBtn = QtWidgets.QPushButton(sweepergui)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout.addWidget(self.startBtn, 6, 1, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(sweepergui)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 4, 1, 1, 2)

        self.retranslateUi(sweepergui)
        QtCore.QMetaObject.connectSlotsByName(sweepergui)

    def retranslateUi(self, sweepergui):
        _translate = QtCore.QCoreApplication.translate
        sweepergui.setWindowTitle(_translate("sweepergui", "Sweeper"))
        self.pushButton.setText(_translate("sweepergui", "Stop"))
        self.groupBox_2.setTitle(_translate("sweepergui", "Parametry sweepu"))
        self.label_3.setText(_translate("sweepergui", "Start [A]"))
        self.lineEdit.setText(_translate("sweepergui", "1e-10"))
        self.label_4.setText(_translate("sweepergui", "End [A]"))
        self.lineEdit_2.setText(_translate("sweepergui", "1e-12"))
        self.label_5.setText(_translate("sweepergui", "Delay [ms]"))
        self.label_6.setText(_translate("sweepergui", "Bodů/dekádu"))
        self.label.setText(_translate("sweepergui", "Druh sweepu"))
        self.radioButton_2.setText(_translate("sweepergui", "Logaritmický"))
        self.radioButton.setText(_translate("sweepergui", "Lineární"))
        self.groupBox.setTitle(_translate("sweepergui", "Ostatní parametry"))
        self.label_2.setText(_translate("sweepergui", "Počet charakteristik"))
        self.label_7.setText(_translate("sweepergui", "Sloupce dat"))
        self.checkBox_4.setText(_translate("sweepergui", "Source"))
        self.checkBox_3.setText(_translate("sweepergui", "Measure"))
        self.checkBox_2.setText(_translate("sweepergui", "Delay"))
        self.checkBox.setText(_translate("sweepergui", "Time"))
        self.label_8.setText(_translate("sweepergui", "Stabilizace [s]"))
        self.startBtn.setText(_translate("sweepergui", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sweepergui = QtWidgets.QDialog()
    ui = Ui_sweepergui()
    ui.setupUi(sweepergui)
    sweepergui.show()
    sys.exit(app.exec_())

